interface McpToolDefinition {
  name: string;
  description: string;
  inputSchema: {
    type: 'object';
    properties: Record<string, unknown>;
    required?: string[];
  };
}

interface McpToolExport {
  tools: McpToolDefinition[];
  callTool: (name: string, args: Record<string, unknown>) => Promise<unknown>;
  meter?: { credits: number };
  cost?: Record<string, unknown>;
  provider?: string;
}

/**
 * Developer Feeds MCP.
 *
 * Software development & engineering — programming, infrastructure and company engineering blogs.
 * CF-robust RSS / Atom / RDF reader over a curated, edge-verified registry; on a
 * Cloudflare egress block it falls back to the rss2json proxy. (Generated by
 * scripts/gen-feeds-packs.mjs from scripts/feeds-registry.mjs — do not hand-edit.)
 */


const UA = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36';
const PROXY = 'https://api.rss2json.com/v1/api.json';
const MAX_ITEMS = 50;

interface FeedDef { title: string; url: string; category: string; source: string; description: string }

const FEEDS: Record<string, FeedDef> = {
  'github-blog': { title: "The GitHub Blog", url: "https://github.blog/feed/", category: "dev", source: "github.blog", description: "GitHub product & engineering" },
  'stackoverflow-blog': { title: "Stack Overflow Blog", url: "https://stackoverflow.blog/feed/", category: "dev", source: "stackoverflow.blog", description: "Software development articles" },
  'aws-blog': { title: "AWS News Blog", url: "https://aws.amazon.com/blogs/aws/feed/", category: "dev", source: "aws.amazon.com", description: "Amazon Web Services announcements" },
  'google-dev': { title: "Google Developers Blog", url: "https://developers.googleblog.com/feeds/posts/default", category: "dev", source: "developers.googleblog.com", description: "Google developer platform news" },
  'web-dev': { title: "web.dev", url: "https://web.dev/feed.xml", category: "dev", source: "web.dev", description: "Modern web development (Google)" },
  'mozilla-hacks': { title: "Mozilla Hacks", url: "https://hacks.mozilla.org/feed/", category: "dev", source: "hacks.mozilla.org", description: "Web platform & Firefox engineering" },
  smashing: { title: "Smashing Magazine", url: "https://www.smashingmagazine.com/feed/", category: "dev", source: "smashingmagazine.com", description: "Web design & front-end development" },
  'css-tricks': { title: "CSS-Tricks", url: "https://css-tricks.com/feed/", category: "dev", source: "css-tricks.com", description: "CSS & front-end techniques" },
  'cloudflare-blog': { title: "Cloudflare Blog", url: "https://blog.cloudflare.com/rss/", category: "dev", source: "blog.cloudflare.com", description: "Cloudflare engineering & product" },
  'netflix-tech': { title: "Netflix TechBlog", url: "https://netflixtechblog.com/feed", category: "dev", source: "netflixtechblog.com", description: "Netflix engineering" },
  infoq: { title: "InfoQ", url: "https://feed.infoq.com/", category: "dev", source: "infoq.com", description: "Software architecture & development news" },
  'dev-to': { title: "DEV Community", url: "https://dev.to/feed", category: "dev", source: "dev.to", description: "Developer community articles" },
  lwn: { title: "LWN.net", url: "https://lwn.net/headlines/rss", category: "dev", source: "lwn.net", description: "Linux & open-source development news" },
  'martin-fowler': { title: "Martin Fowler", url: "https://martinfowler.com/feed.atom", category: "dev", source: "martinfowler.com", description: "Software design & architecture" },
  'stripe-blog': { title: "Stripe Blog", url: "https://stripe.com/blog/feed.rss", category: "dev", source: "stripe.com", description: "Stripe engineering & product" },
  'go-blog': { title: "The Go Blog", url: "https://go.dev/blog/feed.atom", category: "dev", source: "go.dev", description: "Go programming language news" },
  'rust-blog': { title: "Rust Blog", url: "https://blog.rust-lang.org/feed.xml", category: "dev", source: "blog.rust-lang.org", description: "Rust programming language news" },
  phoronix: { title: "Phoronix", url: "https://www.phoronix.com/rss.php", category: "dev", source: "phoronix.com", description: "Linux hardware & open-source benchmarks" },
  'daring-fireball': { title: "Daring Fireball", url: "https://daringfireball.net/feeds/main", category: "dev", source: "daringfireball.net", description: "Apple, design & technology (John Gruber)" },
  'kubernetes-blog': { title: "Kubernetes Blog", url: "https://kubernetes.io/feed.xml", category: "dev", source: "kubernetes.io", description: "Kubernetes project news" },
  omgubuntu: { title: "OMG! Ubuntu", url: "https://www.omgubuntu.co.uk/feed", category: "dev", source: "omgubuntu.co.uk", description: "Ubuntu & Linux desktop news" },
  'meta-eng': { title: "Meta Engineering", url: "https://engineering.fb.com/feed/", category: "dev", source: "engineering.fb.com", description: "Meta engineering blog" },
  supabase: { title: "Supabase", url: "https://supabase.com/rss.xml", category: "dev", source: "supabase.com", description: "Supabase product & engineering" },
  'discord-blog': { title: "Discord Blog", url: "https://discord.com/blog/rss.xml", category: "dev", source: "discord.com", description: "Discord product & engineering" },
  vercel: { title: "Vercel", url: "https://vercel.com/atom", category: "dev", source: "vercel.com", description: "Vercel & frontend-platform news" },
  'arxiv-cs-se': { title: "arXiv cs.SE", url: "https://rss.arxiv.org/rss/cs.SE", category: "dev", source: "arxiv.org", description: "arXiv Software Engineering preprints (cs.SE)" },
};

const tools: McpToolExport['tools'] = [
  {
    name: 'list_feeds',
    description: 'List the curated software-development feeds (id, title, category, source). Optionally filter by category (dev) or keyword. Pass an id to read_feed.',
    inputSchema: {
      type: 'object',
      properties: {
        category: { type: 'string', description: 'Filter by category: dev.' },
        query: { type: 'string', description: 'Keyword to match in feed title/source/description.' },
      },
    },
  },
  {
    name: 'read_feed',
    description: 'Read a curated software-development feed by its id (from list_feeds). Returns normalized items (title, link, published, summary). Optionally filter items by keyword.',
    inputSchema: {
      type: 'object',
      properties: {
        feed: { type: 'string', description: 'Curated feed id (from list_feeds).' },
        query: { type: 'string', description: 'Keyword filter over item title/summary.' },
        limit: { type: 'number', description: 'Max items (1-50, default 20).' },
      },
      required: ['feed'],
    },
  },
  {
    name: 'fetch_feed',
    description: 'Fetch and normalize any RSS / Atom / RDF feed by URL. CF-robust: fetches directly and falls back to a proxy if the source blocks the gateway. Use list_feeds first for curated sources.',
    inputSchema: {
      type: 'object',
      properties: {
        url: { type: 'string', description: 'Feed URL, e.g. "https://news.ycombinator.com/rss".' },
        query: { type: 'string', description: 'Keyword filter over item title/summary.' },
        limit: { type: 'number', description: 'Max items (1-50, default 20).' },
      },
      required: ['url'],
    },
  },
];

async function callTool(name: string, args: Record<string, unknown>): Promise<unknown> {
  switch (name) {
    case 'list_feeds':
      return listFeeds(args);
    case 'read_feed': {
      const id = String(args.feed ?? '').trim();
      const def = FEEDS[id];
      if (!def) throw new Error(`Unknown feed "${args.feed}". Use list_feeds to see valid ids.`);
      return readFeed(def.url, args, { id, ...def });
    }
    case 'fetch_feed': {
      const url = String(args.url ?? '').trim();
      if (!/^https?:\/\//i.test(url)) throw new Error('Pass a valid feed `url` (http/https).');
      return readFeed(url, args);
    }
    default:
      throw new Error(`Unknown tool: ${name}`);
  }
}

function listFeeds(args: Record<string, unknown>): unknown {
  const cat = typeof args.category === 'string' ? args.category.trim().toLowerCase() : '';
  const q = typeof args.query === 'string' ? args.query.trim().toLowerCase() : '';
  const feeds = Object.entries(FEEDS)
    .filter(([, d]) => (!cat || d.category === cat) && (!q || `${d.title} ${d.source} ${d.description}`.toLowerCase().includes(q)))
    .map(([id, d]) => ({ id, title: d.title, category: d.category, source: d.source, description: d.description }));
  return { categories: [...new Set(Object.values(FEEDS).map((d) => d.category))].sort(), count: feeds.length, feeds };
}

async function readFeed(url: string, args: Record<string, unknown>, meta?: Record<string, unknown>): Promise<unknown> {
  const limit = clamp(numArg(args.limit, 20), 1, MAX_ITEMS);
  const q = typeof args.query === 'string' ? args.query.trim().toLowerCase() : '';
  const { items, via } = await getFeed(url);
  let out = items;
  if (q) out = out.filter((i) => `${i.title} ${i.summary}`.toLowerCase().includes(q));
  return {
    feed: meta ? { id: meta.id, title: meta.title, source: meta.source } : { url },
    via,
    total_matching: out.length,
    count: Math.min(out.length, limit),
    items: out.slice(0, limit),
  };
}

interface FeedItem { title: string; link: string; published?: string; summary?: string; author?: string; categories?: string[]; id?: string }

async function getFeed(url: string): Promise<{ items: FeedItem[]; via: string }> {
  try {
    const res = await fetch(url, { headers: { 'User-Agent': UA, Accept: 'application/rss+xml, application/atom+xml, application/xml, text/xml, */*' } });
    if (res.ok) {
      const xml = await res.text();
      if (/<(item|entry)[\s>]/i.test(xml)) return { items: parseFeed(xml), via: 'direct' };
    }
  } catch {
    /* fall through to proxy */
  }
  const pres = await fetch(`${PROXY}?rss_url=${encodeURIComponent(url)}&count=${MAX_ITEMS}`, { headers: { 'User-Agent': UA, Accept: 'application/json' } });
  const body = (await pres.json().catch(() => ({}))) as { status?: string; items?: ProxyItem[] };
  if (body.status === 'ok' && Array.isArray(body.items)) {
    return {
      items: body.items.map((i) => ({
        title: clean(i.title), link: i.link || '', published: i.pubDate || undefined,
        summary: clean(i.description)?.slice(0, 500) || undefined, author: i.author || undefined,
        categories: Array.isArray(i.categories) ? i.categories : undefined, id: i.guid || i.link,
      })),
      via: 'proxy',
    };
  }
  throw new Error(`Feed unreachable: ${url} (blocked directly and via proxy). The source may block datacenter egress.`);
}

interface ProxyItem { title?: string; link?: string; pubDate?: string; description?: string; author?: string; categories?: string[]; guid?: string }

function parseFeed(xml: string): FeedItem[] {
  const out: FeedItem[] = [];
  const blocks = xml.match(/<(item|entry)[\s>][\s\S]*?<\/\1>/gi) ?? [];
  for (const b of blocks) {
    const link = extractLink(b);
    out.push({
      title: clean(tag(b, 'title')),
      link,
      published: tag(b, 'pubDate') || tag(b, 'published') || tag(b, 'updated') || tag(b, 'dc:date') || undefined,
      summary: clean(tag(b, 'description') || tag(b, 'summary') || tag(b, 'content:encoded') || tag(b, 'content'))?.slice(0, 500) || undefined,
      author: clean(tag(b, 'dc:creator') || authorName(b)) || undefined,
      categories: cats(b),
      id: tag(b, 'guid') || tag(b, 'id') || link,
    });
  }
  return out;
}

function extractLink(b: string): string {
  const rss = b.match(/<link>([\s\S]*?)<\/link>/i);
  if (rss && rss[1].trim()) return clean(rss[1]);
  const alt = b.match(/<link[^>]*rel=["']alternate["'][^>]*href=["']([^"']+)["']/i) || b.match(/<link[^>]*href=["']([^"']+)["']/i);
  return alt ? alt[1].trim() : '';
}
function authorName(b: string): string {
  const a = b.match(/<author>([\s\S]*?)<\/author>/i);
  if (!a) return '';
  const name = a[1].match(/<name>([\s\S]*?)<\/name>/i);
  return name ? name[1] : a[1];
}
function cats(b: string): string[] | undefined {
  const list: string[] = [];
  for (const m of b.matchAll(/<category[^>]*?(?:term=["']([^"']+)["'][^>]*)?>([\s\S]*?)<\/category>/gi)) {
    const v = clean(m[1] || m[2]);
    if (v) list.push(v);
  }
  for (const m of b.matchAll(/<category[^>]*term=["']([^"']+)["'][^>]*\/>/gi)) list.push(m[1]);
  return list.length ? [...new Set(list)].slice(0, 10) : undefined;
}
function tag(xml: string, name: string): string {
  const m = xml.match(new RegExp(`<${name.replace(':', '\\:')}[^>]*>([\\s\\S]*?)<\\/${name.replace(':', '\\:')}>`, 'i'));
  return m ? unwrap(m[1]) : '';
}
function unwrap(s: string): string {
  const m = s.trim().match(/^<!\[CDATA\[([\s\S]*?)\]\]>$/);
  return (m ? m[1] : s).trim();
}
function clean(s: unknown): string {
  if (typeof s !== 'string') return '';
  return s
    .replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g, '$1')
    .replace(/&lt;/g, '<').replace(/&gt;/g, '>')
    .replace(/<\/?[a-zA-Z][^>]*>/g, ' ')
    .replace(/&#(\d+);/g, (_, d) => String.fromCodePoint(Number(d)))
    .replace(/&#x([0-9a-f]+);/gi, (_, h) => String.fromCodePoint(parseInt(h, 16)))
    .replace(/&quot;/g, '"').replace(/&#39;|&apos;/g, "'").replace(/&nbsp;/g, ' ').replace(/&amp;/g, '&')
    .replace(/\s+/g, ' ').trim();
}
function numArg(v: unknown, dflt: number): number {
  const n = typeof v === 'number' ? v : typeof v === 'string' ? Number(v) : NaN;
  return Number.isFinite(n) ? n : dflt;
}
function clamp(n: number, lo: number, hi: number): number {
  return Math.max(lo, Math.min(hi, Math.trunc(n)));
}

export default { tools, callTool, meter: { credits: 1 } } satisfies McpToolExport;
